// <auto-generated />
using System;
using AttendDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RTUAttendAPI.AttendDatabase.Models;

#nullable disable

namespace AttendDatabase.Migrations
{
    [DbContext(typeof(AttendDbContext))]
    [Migration("20230801194209_LessonEntityUpdated")]
    partial class LessonEntityUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "student_membership_role", new[] { "unknown", "student", "elder", "vice_elder" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "student_membership_type", new[] { "unknown", "active", "inactive" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("discipline", (string)null);
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.DisciplineVisitingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FkDisciplineId")
                        .HasColumnType("uuid")
                        .HasColumnName("fk_discipline_id");

                    b.Property<Guid>("FkVisitingLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("fk_visiting_log_id");

                    b.HasKey("Id");

                    b.HasIndex("FkDisciplineId");

                    b.HasIndex("FkVisitingLogId");

                    b.ToTable("disciplines_visiting_logs", (string)null);
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auditorium")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auditorium");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid")
                        .HasColumnName("fk_discipline_id");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.Property<Guid>("VisitingLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("fk_visiting_log_id");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("VisitingLogId");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.NsiHuman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Middlename")
                        .HasColumnType("text")
                        .HasColumnName("middlename");

                    b.HasKey("Id");

                    b.ToTable("nsi_human", (string)null);
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.NsiStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("NsiHumanId")
                        .HasColumnType("uuid")
                        .HasColumnName("fk_nsi_human_id");

                    b.HasKey("Id");

                    b.HasIndex("NsiHumanId");

                    b.ToTable("nsi_student", (string)null);
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("semester_pkey");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("semester", (string)null);
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.StudentMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<StudentMembershipRole>("MembershipRole")
                        .HasColumnType("student_membership_role")
                        .HasColumnName("membership_role");

                    b.Property<StudentMembershipType>("MembershipType")
                        .HasColumnType("student_membership_type")
                        .HasColumnName("membership_type");

                    b.Property<Guid>("NsiStudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("nsi_student_id");

                    b.Property<Guid>("VisitingLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("visiting_log_id");

                    b.HasKey("Id")
                        .HasName("student_membership_pkey");

                    b.HasIndex("VisitingLogId");

                    b.HasIndex("NsiStudentId", "VisitingLogId")
                        .IsUnique()
                        .HasDatabaseName("student_membership_student_in_group_once");

                    b.ToTable("student_membership", (string)null);
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NsiHumanId")
                        .HasColumnType("uuid")
                        .HasColumnName("fk_nsi_human_id");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("NsiHumanId");

                    b.ToTable("teacher", (string)null);
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.VisitingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("semester_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("visiting_log_pkey");

                    b.HasIndex("SemesterId");

                    b.ToTable("visiting_log", (string)null);
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.DisciplineVisitingLog", b =>
                {
                    b.HasOne("RTUAttendAPI.AttendDatabase.Models.Discipline", "FkDisciplineVisitingLog")
                        .WithMany("VisitingLogs")
                        .HasForeignKey("FkDisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("disciplines_fk_visiting_logs_foreign");

                    b.HasOne("RTUAttendAPI.AttendDatabase.Models.VisitingLog", "FkVisitingLogDiscipline")
                        .WithMany("Disciplines")
                        .HasForeignKey("FkVisitingLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("visiting_logs_fk_discilplines_logs_foreign");

                    b.Navigation("FkDisciplineVisitingLog");

                    b.Navigation("FkVisitingLogDiscipline");
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.Lesson", b =>
                {
                    b.HasOne("RTUAttendAPI.AttendDatabase.Models.Discipline", "Discipline")
                        .WithMany("Lessons")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RTUAttendAPI.AttendDatabase.Models.VisitingLog", "VisitingLog")
                        .WithMany("Lessons")
                        .HasForeignKey("VisitingLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("VisitingLog");
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.NsiStudent", b =>
                {
                    b.HasOne("RTUAttendAPI.AttendDatabase.Models.NsiHuman", "NsiHuman")
                        .WithMany("NsiStudents")
                        .HasForeignKey("NsiHumanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NsiHuman");
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.StudentMembership", b =>
                {
                    b.HasOne("RTUAttendAPI.AttendDatabase.Models.NsiStudent", "NsiStudent")
                        .WithMany("StudentMemberships")
                        .HasForeignKey("NsiStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RTUAttendAPI.AttendDatabase.Models.VisitingLog", "VisitingLog")
                        .WithMany("StudentMemberships")
                        .HasForeignKey("VisitingLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NsiStudent");

                    b.Navigation("VisitingLog");
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.Teacher", b =>
                {
                    b.HasOne("RTUAttendAPI.AttendDatabase.Models.Lesson", "Lesson")
                        .WithMany("Teachers")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RTUAttendAPI.AttendDatabase.Models.NsiHuman", "NsiHuman")
                        .WithMany("Teachers")
                        .HasForeignKey("NsiHumanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("NsiHuman");
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.VisitingLog", b =>
                {
                    b.HasOne("RTUAttendAPI.AttendDatabase.Models.Semester", "Semester")
                        .WithMany("VisitingLogs")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.Discipline", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("VisitingLogs");
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.Lesson", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.NsiHuman", b =>
                {
                    b.Navigation("NsiStudents");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.NsiStudent", b =>
                {
                    b.Navigation("StudentMemberships");
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.Semester", b =>
                {
                    b.Navigation("VisitingLogs");
                });

            modelBuilder.Entity("RTUAttendAPI.AttendDatabase.Models.VisitingLog", b =>
                {
                    b.Navigation("Disciplines");

                    b.Navigation("Lessons");

                    b.Navigation("StudentMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
